# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gcsm <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call('_GCSM_gcsm', PACKAGE = 'GCSM', x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

gcsm_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call('_GCSM_gcsm_sw', PACKAGE = 'GCSM', x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

gcsm_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call('_GCSM_gcsm_tw', PACKAGE = 'GCSM', xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

