# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname gcsm
#' @export
cmsc <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc`, x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

#' @rdname gcsm_sw
#' @export
cmsc_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call(`_GCSM_cmsc_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

#' @rdname gcsm_tw
#' @export
cmsc_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

#' @rdname gcsm
#' @export
cmsc_e1 <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc_e1`, x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

#' @rdname gcsm_sw
#' @export
cmsc_e1_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call(`_GCSM_cmsc_e1_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

#' @rdname gcsm_tw
#' @export
cmsc_e1_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc_e1_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

#' @rdname gcsm
#' @export
cmsc_e2 <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc_e2`, x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

#' @rdname gcsm_sw
#' @export
cmsc_e2_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call(`_GCSM_cmsc_e2_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

#' @rdname gcsm_tw
#' @export
cmsc_e2_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc_e2_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

#' Composite similarity between vectors
#'
#' Compute composite measures, GCSM or CMSC, between two vectors.
#' @param x A vector.
#' @param y The other vector.
#' @param rescale Rescale or not before computation.
#' @param xmin,xmax,ymin,ymax Rescale parameters.
#' If `NA_real_`, will set as global minimum and maximum in `x` and `y`, respectively.
#' @param comp Variable to return.
#' If `"si"`, the composite measure, if `"s1"`,`"s2"` or `"s3"`, the corresponding component.
#' @return A number.
#' @export
#' @examples
#' # mean shift
#' x = runif(9)
#' y = 1 - x # y is the perfect antianalog of x
#' ## similarity
#' gcsm(x, x)
#' cmsc(x, x)
#' gcsm(x, x - 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' cmsc(x, x - 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' gcsm(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' cmsc(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' ## dissimilarity
#' gcsm(y, x)
#' gcsm(y, x - 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' gcsm(y, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#'
#' # random noise
#' noise = rnorm(9, mean = 0, sd = 0.2)
#' ## similarity
#' gcsm(x, x + noise, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' cmsc(x, x + noise, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' ## dissimilarity
#' gcsm(y, x + noise, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#'
gcsm <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_gcsm`, x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

#' Composite similarity on spatial windows
#'
#' Compute composite measures, GCSM, CMSC or SSIM, on spatial windows.
#' @param x A vector.
#' @param y The other vector.
#' @param rescale Rescale or not before computation.
#' @param xmin,xmax,ymin,ymax Rescale parameters.
#' If `NA_real_`, will set as global minimum and maximum in `x` and `y`, respectively.
#' @param ksize Side length of spatial windows.
#' @param globe Are data at the global scale?
#' If `TRUE`, two vertical borders will be padded before computation.
#' @param comp Variable to return.
#' If `"si"`, the composite measure, if `"s1"`,`"s2"` or `"s3"`, the corresponding component.
#' @return A matrix.
#' @export
#' @examples
#' x = matrix(runif(36), nrow = 6, ncol = 6)
#'
#' gcsm_sw(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1, ksize = 3)
#' cmsc_sw(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1, ksize = 3)
#' ssim_sw(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1, ksize = 3)
#'
gcsm_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call(`_GCSM_gcsm_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

#' Composite similarity on temporal windows
#'
#' Compute composite measures, GCSM or CMSC, on temporal windows.
#' @param xxx A 3-d array with the 3rd dimension representing time.
#' @param yyy The other 3-d array.
#' @param rescale Rescale or not before computation.
#' @param xmin,xmax,ymin,ymax Rescale parameters.
#' If `NA_real_`, will set as global minimum and maximum in `xxx` and `yyy`, respectively.
#' @param comp Variable to return.
#' If `"si"`, the composite measure, if `"s1"`,`"s2"` or `"s3"`, the corresponding component.
#' @return A matrix.
#' @export
#' @examples
#' x = array(runif(81), dim = c(3, 3, 9))
#'
#' gcsm_tw(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#' cmsc_tw(x, x + 0.2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
#'
gcsm_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_gcsm_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

#' @rdname gcsm_sw
#' @param sigma Standard deviation of Gaussian weighting function
#' depending on the distance between the cell and kernel center.
#' @export
ssim_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 11, sigma = 1.5, globe = FALSE, comp = "si") {
    .Call(`_GCSM_ssim_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, sigma, globe, comp)
}

