# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmsc <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc`, x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

cmsc_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call(`_GCSM_cmsc_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

cmsc_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_cmsc_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

gcsm <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_gcsm`, x, y, rescale, xmin, xmax, ymin, ymax, comp)
}

gcsm_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, comp = "si") {
    .Call(`_GCSM_gcsm_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, comp)
}

gcsm_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, comp = "si") {
    .Call(`_GCSM_gcsm_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, comp)
}

